version: '3.9'
services:
  mysql:
    image: container-registry.oracle.com/mysql/community-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: thepass
    volumes: [db-data:/var/lib/mysql]
    ports:
      - "127.0.0.1:3306:3306"

  localstack_s3:
    image: localstack/localstack:s3-latest
    environment:
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack" 
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis:7

  app:
    build: .
    depends_on: [db, localstack, redis]
    environment:
      - DB_DSN=dbuser:thepass@tcp(mysql:3306)/todo
      - S3_ENDPOINT=http://localstack_s3:4566
volumes:
  db-data:
